face_recog/urls.py
from django.urls import path

from face_recog import views

app_name = 'face_recog'
urlpatterns = [
    path('register/', views.register_face, name='register_face')
]

paqueue/urls.py
from django.contrib import admin
from django.urls import path, include

import queuer, face_recog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('queuer.urls')),
    path('kyc/', include('face_recog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

queuer/urls.py
from django.urls import path

from queuer import views

app_name = 'queuer'
urlpatterns = [
    path('queues/<int:queue_id>/', views.detail, name='detail'),
    path('current_number/<int:queue_id>/', views.current_number, name='current_number'),
    path('api/increment/', views.increment, name='increment'),
    path('get_wallet/', views.get_wallet, name='get_wallet'),
    path('get_queue/<int:queue_id>/', views.get_queue, name='get_queue'),
    path('assign_number/', views.assign_number, name='assign_number'),
    path('', views.listing, name='listing'),
    path('compare_faces/', views.compare_faces, name='compare_faces'),
    path('login/', views.login, name='login')
]

blockchain/models.py
from django.db import models

class Contract(models.Model):
    user = models.CharField(max_length=42)
    queue_id = models.IntegerField(default=0)
    number = models.IntegerField(default=0)

    def __str__(self):
        return '%s' % self.name

face_recog/models.py
import json
import os
from jsonfield import JSONField
from django.db import models
from django.contrib.auth.models import User

from face_recog.utils import encode_photo


class FaceData(models.Model):
    user = models.ForeignKey(User, on_delete='models.CASCADE',
        related_name='face_data')
    encoded = JSONField()

    def encode_photo(self, path):
        self.encoded = encode_photo(path)
        self.save()

    def __str__(self):
        return self.user.username

queuer/models.py
from django.db import models
from django.contrib.auth.models import User


class Queue(models.Model):
    name = models.CharField(max_length=256)
    current_number = models.PositiveIntegerField()
    latest_assigned = models.PositiveIntegerField()
    
    def __str__(self):
        return self.name + " Queue"

    def get_next_in_line(self):
        self.current_number += 1
        return self.current_number


class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete='models.CASCADE', related_name='wallet')
    value = models.FloatField(default=0.0)

    def __str__(self):
        return self.user.username

    def payment(self):
        self.value -= 3
        self.save()


class UserQueue(models.Model):
    user = models.ForeignKey(User, on_delete='models.CASCADE')
    queue = models.ForeignKey(Queue, on_delete='models.CASCADE')
    number = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "%s - %s" % (self.user.username, self.queue)

    def assign_number(self):
        self.number = self.queue.latest_assigned + 1
        self.save()

        self.queue.latest_assigned += 1
        self.queue.save()

face_recog/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

blockchain/views.py
from django.shortcuts import render

# Create your views here.

face_recog/views.py
import base64
from django.shortcuts import render
from django.core.files import File
from django.contrib.auth.models import User
from face_recog.models import FaceData


def register_face(request):
    if request.method == 'GET':
        return render(request, 'show_camera.html')

    elif request.method == 'POST':
        user = User.objects.get(username=request.POST['user'])
        m, created = FaceData.objects.update_or_create(user=user)
        img_data = request.POST['image']
        format, imgstr = img_data.split(';base64,')
        img = base64.b64decode(imgstr)
        filename = 'tmp/%d' % user.id
        with open(filename, 'wb') as f:
            f.write(img)

        m.save()
        m.encode_photo(filename)

        return render(request, 'show_camera.html')

queuer/views.py
from django.shortcuts import render
import base64

from django.http import HttpResponse
from .models import Queue, Wallet, UserQueue
from face_recog.models import FaceData
from face_recog.utils import compare_photo
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, logout
from django.contrib.auth.models import User

import json

def listing(request):
    active_queues = Queue.objects.all()
    context = {
        'active_queues' : active_queues
    }
    return render(request, 'queuer/listing.html', context)


def detail(request, queue_id):
    inspected_queue = Queue.objects.get(pk=queue_id)
    context = {
        'inspected_queue' : inspected_queue
    }
    return render(request, 'queuer/detail.html', context)


def increment(request):
    queue_id = request.POST['queue_id']
    inspected_queue = Queue.objects.get(pk=queue_id)
    inspected_queue.get_next_in_line()
    inspected_queue.save()
    return HttpResponse(inspected_queue.current_number)


def compare_faces(request):
    queue = Queue.objects.get(name=request.POST['queue_name'])
    target = UserQueue.objects.get(queue=queue, number=queue.current_number)
    target_face = FaceData.objects.get(user=target.user)

    img_data = request.POST['image']
    format, imgstr = img_data.split(';base64,')
    img = base64.b64decode(imgstr)
    filename = '/tmp/%s' % 'target_face'
    with open(filename, 'wb') as f:
        f.write(img)

    result = compare_photo(target_face.encoded, filename)
    if result==True:
        queue.current_number += 1
        queue.save()

    return HttpResponse(result)


@csrf_exempt
def current_number(request, queue_id):
    inspected_queue = Queue.objects.get(pk=queue_id)

    return HttpResponse(inspected_queue.current_number)


@csrf_exempt
def get_wallet(request):
    user = User.objects.get(username=request.GET['user_id'])
    wallet = Wallet.objects.get(user=user)
    response = {'wallet_value': wallet.value}

    return HttpResponse(json.dumps(response), 'application/json')


@csrf_exempt
def get_queue(request, queue_id):
    user = User.objects.get(username=request.GET['user_id'])
    queue = Queue.objects.get(id=queue_id)
    user_queue, created = UserQueue.objects.get_or_create(
        user=user, queue=queue,
        defaults={
            'number': queue.latest_assigned + 1
        }
    )

    response = {'number': user_queue.number}
    return HttpResponse(json.dumps(response), 'application/json')


@csrf_exempt
def assign_number(request):
    queue_id = request.POST['queue_id']
    user = User.objects.get(username=request.POST['user_id'])
    wallet = Wallet.objects.get(user=user)

    queue = Queue.objects.get(id=queue_id)
    user_queue, created = UserQueue.objects.update_or_create(
        user=user, queue=queue,
        defaults={
            'number': queue.latest_assigned + 1
        }
    )

    queue.latest_assigned += 1
    queue.save()
    response = {}
    if wallet.value >= 3:
        wallet.payment()
        response['assigned_number'] = user_queue.number
        status = 201
    else:
        response['assigned_number'] = 0
        status = 400

    return HttpResponse(json.dumps(response), 'application/json', status=status)

    
@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = request.user
    user = authenticate(username=username, password=password)

    if not user:
        response = {'message': 'Invalid username/password', 'status':'error'}
        return HttpResponse(json.dumps(response), 'application/json')
    else:
        response = {'message': 'Login Success', 'status':'success'}
        return HttpResponse(json.dumps(response), 'application/json')

face_recog/templates/show_camera.html
<html>
<body>
	<script src="/static/kyc/webcam.js"></script>
	<div id="my_camera" style="width:320px; height:240px;"></div>
	<h3> User Face: </h3>
	<div id="my_base"></div>
	<form action="{% url 'face_recog:register_face' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
        <input type="hidden" id="image" name="image">
        <input type="text" id="user" name="user">
	    <input type="submit" value="Submit" />
	</form>

	<script language="JavaScript">
    Webcam.attach('#my_camera');

    function take_model() {
        Webcam.snap(function(data_uri) {
            document.getElementById('my_base').innerHTML = '<img src="' + data_uri + '"/>';
            document.getElementById('image').value = data_uri;
        });
    }
</script>

<a href="javascript:void(take_model())">Take UserFace</a>

</body>
</html>

face_recog/templates/upload.html
<html>
<body>
	<form action="{% url 'face_recognition:register_face' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
	    <p>
			<input id="id_image" type="file" class="" name="image">
			<input type="text" name="user" placeholder="User">
	    </p>
	    <input type="submit" value="Submit" />
	</form>
</body>
</html>

queuer/templates/queuer/detail.html
<!DOCTYPE html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    </head>
    <body>
        <center>PA-Q!</center>
        {{ inspected_queue.name }}
        <div id="current_num">{{ inspected_queue.current_number }}</div>

        <script src="/static/kyc/webcam.js"></script>
        <div id="my_camera" style="width:320px; height:240px;"></div>
        <h3> User Face: </h3>
        <div id="my_base"></div>
        <form action="{% url 'queuer:compare_faces' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" id="image" name="image">
            <input type="hidden" id="queue_name" name="queue_name" value="{{ inspected_queue.name }}">
            <input type="submit" value="Submit" />
        </form>

        <script language="JavaScript">
            Webcam.attach('#my_camera');

            function take_model() {
                Webcam.snap(function(data_uri) {
                    document.getElementById('my_base').innerHTML = '<img src="' + data_uri + '"/>';
                    document.getElementById('image').value = data_uri;
                });
            }
        </script>

<a href="javascript:void(take_model())">Take UserFace</a>
    </body>
<html>

queuer/templates/queuer/listing.html
<!DOCTYPE html>
    <head>
    </head>
    <body>
        <center>PA-Q!</center>
        {% if active_queues %}
            {% for queue in active_queues %}
                <a href="{% url 'queuer:detail' queue.id %}">{{ queue.name }}</a>
                <br/>
            {% endfor %}
        {% else %}
            <p>No queues are available.</p>
        {% endif %}
    </body>
<html>